require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe CommentsController, type: :controller do
  let(:article) { create :article }

  describe "GET /index" do
    subject { get :index, params: { article_id: article.id } }

    it "renders a successful response" do
      subject
      expect(response).to have_http_status(:ok)
    end

    it 'should return only comments belonging to article' do
      comment = create :comment, article: article
      create :comment
      subject
      expect(json_array.length).to eq(1)
      expect(json_array.first['id']).to eq(comment.id)
    end

    it 'should have a proper json body' do
      comment = create :comment, article: article
      subject
      expect(json_array.first['content']).to eq(comment.content)
    end

    it 'should have related objects information in the response' do
      user = create :user
      comment = create :comment, article: article, user: user
      subject
      expect(json_array.first['article_id']).to eq(comment.article_id)
      expect(json_array.first['user_id']).to eq(comment.user_id)
    end
  end

  describe "POST /create" do
    let(:valid_attributes) { { content: 'My comment' } }
    let(:invalid_attributes) { { content: '' } }

    context "when not authorized" do
      subject { post :create, params: { article_id: article.id } }
      it_behaves_like 'forbidden_requests'
    end

    context "when authorized" do
      let(:user) { create :user }
      let(:access_token) { user.create_access_token }
      before { request.headers['authorization'] = "Bearer #{access_token.token}" }

      context "with valid parameters" do
        subject { post :create, params: { article_id: article.id, comment: valid_attributes } }
        it "creates a new Comment" do
          expect { subject }.to change(article.comments, :count).by(1)
        end

        it 'returns 201 status code' do
          subject
          expect(response).to have_http_status(:created)
        end

        it "renders a JSON response with the new comment" do
          subject
          expect(json_array).to include({ 'content' => 'My comment' })
        end
      end

      context "with invalid parameters" do
        subject { post :create, params: { article_id: article.id, comment: invalid_attributes } }

        it "does not create a new Comment" do
          subject
          expect { subject }.to change { article.comments.count }.by(0)
        end

        it 'should return 422 status code' do
          subject
          expect(response).to have_http_status(:unprocessable_entity)
        end

        it "renders a JSON response with errors for the new comment" do
          subject
          pp json_array
          expect(json_array).to eq({ 'content' => ["can't be blank"] })
        end
      end
    end
  end
end
